package com.tinyserver.servlet;

import java.util.Hashtable;

public class MimeUtils {
	static Hashtable<String, String> mimeHash = new Hashtable<String, String>();

	static {
		mimeHash.put("323", "text/h323");
		mimeHash.put("acx", "application/internet-property-stream");
		mimeHash.put("ai", "application/postscript");
		mimeHash.put("aif", "audio/x-aiff");
		mimeHash.put("aifc", "audio/x-aiff");
		mimeHash.put("aiff", "audio/x-aiff");
		mimeHash.put("applet", "text/plain");
		mimeHash.put("asf", "video/x-ms-asf");
		mimeHash.put("asr", "video/x-ms-asf");
		mimeHash.put("asx", "video/x-ms-asf");
		mimeHash.put("au", "audio/basic");
		mimeHash.put("avi", "video/x-msvideo");
		mimeHash.put("axs", "application/olescript");
		mimeHash.put("bas", "text/plain");
		mimeHash.put("bcpio", "application/x-bcpio");
		mimeHash.put("bin", "application/octet-stream");
		mimeHash.put("bmp", "image/bmp");
		mimeHash.put("c", "text/plain");
		mimeHash.put("cat", "application/vnd.ms-pkiseccat");
		mimeHash.put("cdf", "application/x-cdf");
		mimeHash.put("cer", "application/x-x509-ca-cert");
		mimeHash.put("class", "application/octet-stream");
		mimeHash.put("clp", "application/x-msclip");
		mimeHash.put("cmx", "image/x-cmx");
		mimeHash.put("cod", "image/cis-cod");
		mimeHash.put("cpio", "application/x-cpio");
		mimeHash.put("crd", "application/x-mscardfile");
		mimeHash.put("crl", "application/pkix-crl");
		mimeHash.put("crt", "application/x-x509-ca-cert");
		mimeHash.put("csh", "application/x-csh");
		mimeHash.put("css", "text/css");
		mimeHash.put("dcr", "application/x-director");
		mimeHash.put("der", "application/x-x509-ca-cert");
		mimeHash.put("dir", "application/x-director");
		mimeHash.put("dll", "application/x-msdownload");
		mimeHash.put("dms", "application/octet-stream");
		mimeHash.put("doc", "application/msword");
		mimeHash.put("dot", "application/msword");
		
		mimeHash.put("docx", "application/msword");
		mimeHash.put("docm", "application/msword");
		mimeHash.put("dotx", "application/msword");
		mimeHash.put("dotm", "application/msword");
		
		mimeHash.put("dvi", "application/x-dvi");
		mimeHash.put("dxr", "application/x-director");
		mimeHash.put("eps", "application/postscript");
		mimeHash.put("etx", "text/x-setext");
		mimeHash.put("evy", "application/envoy");
		mimeHash.put("exe", "application/octet-stream");
		mimeHash.put("fif", "application/fractals");
		mimeHash.put("flr", "x-world/x-vrml");
		mimeHash.put("gif", "image/gif");
		mimeHash.put("gtar", "application/x-gtar");
		mimeHash.put("gz", "application/x-gzip");
		mimeHash.put("h", "text/plain");
		mimeHash.put("hdf", "application/x-hdf");
		mimeHash.put("hlp", "application/winhlp");
		mimeHash.put("hqx", "application/mac-binhex40");
		mimeHash.put("hta", "application/hta");
		mimeHash.put("htc", "text/x-component");
		mimeHash.put("htm", "text/html");
		mimeHash.put("html", "text/html");
		mimeHash.put("htt", "text/webviewhtml");
		mimeHash.put("ico", "image/x-icon");
		mimeHash.put("ief", "image/ief");
		mimeHash.put("iii", "application/x-iphone");
		mimeHash.put("ins", "application/x-internet-signup");
		mimeHash.put("isp", "application/x-internet-signup");
		mimeHash.put("jfif", "image/pipeg");
		mimeHash.put("jpe", "image/jpeg");
		mimeHash.put("jpeg", "image/jpeg");
		mimeHash.put("jpg", "image/jpeg");
		mimeHash.put("js", "application/x-javascript");
		mimeHash.put("json", "application/json");
		mimeHash.put("latex", "application/x-latex");
		mimeHash.put("lha", "application/octet-stream");
		mimeHash.put("lsf", "video/x-la-asf");
		mimeHash.put("lsx", "video/x-la-asf");
		mimeHash.put("lzh", "application/octet-stream");
		mimeHash.put("m13", "application/x-msmediaview");
		mimeHash.put("m14", "application/x-msmediaview");
		mimeHash.put("m3u", "audio/x-mpegurl");
		mimeHash.put("man", "application/x-troff-man");
		mimeHash.put("mdb", "application/x-msaccess");
		mimeHash.put("me", "application/x-troff-me");
		mimeHash.put("mht", "message/rfc822");
		mimeHash.put("mhtml", "message/rfc822");
		mimeHash.put("mid", "audio/mid");
		mimeHash.put("mny", "application/x-msmoney");
		mimeHash.put("mov", "video/quicktime");
		mimeHash.put("movie", "video/x-sgi-movie");
		mimeHash.put("mp2", "video/mpeg");
		mimeHash.put("mp3", "audio/mpeg");
		mimeHash.put("mpa", "video/mpeg");
		mimeHash.put("mpe", "video/mpeg");
		mimeHash.put("mpeg", "video/mpeg");
		mimeHash.put("mpg", "video/mpeg");
		mimeHash.put("mpp", "application/vnd.ms-project");
		mimeHash.put("mpv2", "video/mpeg");
		mimeHash.put("ms", "application/x-troff-ms");
		mimeHash.put("mvb", "application/x-msmediaview");
		mimeHash.put("nws", "message/rfc822");
		mimeHash.put("oda", "application/oda");
		mimeHash.put("p10", "application/pkcs10");
		mimeHash.put("p12", "application/x-pkcs12");
		mimeHash.put("p7b", "application/x-pkcs7-certificates");
		mimeHash.put("p7c", "application/x-pkcs7-mime");
		mimeHash.put("p7m", "application/x-pkcs7-mime");
		mimeHash.put("p7r", "application/x-pkcs7-certreqresp");
		mimeHash.put("p7s", "application/x-pkcs7-signature");
		mimeHash.put("pbm", "image/x-portable-bitmap");
		mimeHash.put("pdf", "application/pdf");
		mimeHash.put("pfx", "application/x-pkcs12");
		mimeHash.put("pgm", "image/x-portable-graymap");
		mimeHash.put("pko", "application/ynd.ms-pkipko");
		mimeHash.put("pma", "application/x-perfmon");
		mimeHash.put("pmc", "application/x-perfmon");
		mimeHash.put("pml", "application/x-perfmon");
		mimeHash.put("pmr", "application/x-perfmon");
		mimeHash.put("pmw", "application/x-perfmon");
		mimeHash.put("png", "image/png");
		mimeHash.put("pnm", "image/x-portable-anymap");
		mimeHash.put("pot,", "application/vnd.ms-powerpoint");
		mimeHash.put("ppm", "image/x-portable-pixmap");
		mimeHash.put("pps", "application/vnd.ms-powerpoint");
		mimeHash.put("ppt", "application/vnd.ms-powerpoint");
		
		mimeHash.put("pptx", "application/vnd.ms-powerpoint");
		mimeHash.put("pptm", "application/vnd.ms-powerpoint");
		mimeHash.put("ppsx", "application/vnd.ms-powerpoint");
		mimeHash.put("potx", "application/vnd.ms-powerpoint");
		mimeHash.put("potm", "application/vnd.ms-powerpoint");
		mimeHash.put("ppam", "application/vnd.ms-powerpoint");
		
		mimeHash.put("prf", "application/pics-rules");
		mimeHash.put("ps", "application/postscript");
		mimeHash.put("pub", "application/x-mspublisher");
		mimeHash.put("qt", "video/quicktime");
		mimeHash.put("ra", "audio/x-pn-realaudio");
		mimeHash.put("ram", "audio/x-pn-realaudio");
		mimeHash.put("ras", "image/x-cmu-raster");
		mimeHash.put("rgb", "image/x-rgb");
		mimeHash.put("rmi", "audio/mid");
		mimeHash.put("roff", "application/x-troff");
		mimeHash.put("rtf", "application/rtf");
		mimeHash.put("rtx", "text/richtext");
		mimeHash.put("scd", "application/x-msschedule");
		mimeHash.put("sct", "text/scriptlet");
		mimeHash.put("setpay", "application/set-payment-initiation");
		mimeHash.put("setreg", "application/set-registration-initiation");
		mimeHash.put("sh", "application/x-sh");
		mimeHash.put("shar", "application/x-shar");
		mimeHash.put("sit", "application/x-stuffit");
		mimeHash.put("snd", "audio/basic");
		mimeHash.put("spc", "application/x-pkcs7-certificates");
		mimeHash.put("spl", "application/futuresplash");
		mimeHash.put("src", "application/x-wais-source");
		mimeHash.put("sst", "application/vnd.ms-pkicertstore");
		mimeHash.put("stl", "application/vnd.ms-pkistl");
		mimeHash.put("stm", "text/html");
		mimeHash.put("sv4cpio", "application/x-sv4cpio");
		mimeHash.put("sv4crc", "application/x-sv4crc");
		mimeHash.put("t", "application/x-troff");
		mimeHash.put("tar", "application/x-tar");
		mimeHash.put("tcl", "application/x-tcl");
		mimeHash.put("tex", "application/x-tex");
		mimeHash.put("texi", "application/x-texinfo");
		mimeHash.put("texinfo", "application/x-texinfo");
		mimeHash.put("tgz", "application/x-compressed");
		mimeHash.put("tif", "image/tiff");
		mimeHash.put("tiff", "image/tiff");
		mimeHash.put("tr", "application/x-troff");
		mimeHash.put("trm", "application/x-msterminal");
		mimeHash.put("tsv", "text/tab-separated-values");
		mimeHash.put("txt", "text/plain");
		mimeHash.put("uls", "text/iuls");
		mimeHash.put("ustar", "application/x-ustar");
		mimeHash.put("vcf", "text/x-vcard");
		mimeHash.put("vrml", "x-world/x-vrml");
		mimeHash.put("wav", "audio/x-wav");
		mimeHash.put("wcm", "application/vnd.ms-works");
		mimeHash.put("wdb", "application/vnd.ms-works");
		mimeHash.put("wks", "application/vnd.ms-works");
		mimeHash.put("wmf", "application/x-msmetafile");
		mimeHash.put("wps", "application/vnd.ms-works");
		mimeHash.put("wri", "application/x-mswrite");
		mimeHash.put("wrl", "x-world/x-vrml");
		mimeHash.put("wrz", "x-world/x-vrml");
		mimeHash.put("xaf", "x-world/x-vrml");
		mimeHash.put("xbm", "image/x-xbitmap");
		mimeHash.put("xla", "application/vnd.ms-excel");
		mimeHash.put("xlc", "application/vnd.ms-excel");
		mimeHash.put("xlm", "application/vnd.ms-excel");
		mimeHash.put("xls", "application/vnd.ms-excel");
		mimeHash.put("xlt", "application/vnd.ms-excel");
		
		mimeHash.put("xlsx", "application/vnd.ms-excel");
		mimeHash.put("xlsm", "application/vnd.ms-excel");
		mimeHash.put("xltx", "application/vnd.ms-excel");
		mimeHash.put("xltm", "application/vnd.ms-excel");
		mimeHash.put("xlsb", "application/vnd.ms-excel");
		mimeHash.put("xlam", "application/vnd.ms-excel");
		
		mimeHash.put("xlw", "application/vnd.ms-excel");
		mimeHash.put("xof", "x-world/x-vrml");
		mimeHash.put("xpm", "image/x-xpixmap");
		mimeHash.put("xwd", "image/x-xwindowdump");
		mimeHash.put("z", "application/x-compress");
		mimeHash.put("zip", "application/zip");
	}

	private MimeUtils() {}

	public static String getMimeType(String fileName) {
		int index = -1;
		if (fileName == null || (index = fileName.lastIndexOf('.')) < 0) {
			return "application/octet-stream";
		}
		String ext = fileName.substring(index + 1).trim().toLowerCase();
		String mimeType = (String) mimeHash.get(ext);
		return mimeType == null ? "application/octet-stream" : mimeType;
	}
}
